name: CreateTFStorageAccount

on:
  workflow_dispatch:

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: read

jobs:
  deploytfstorageaccount:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: true

      - name: Add TF Storage Account
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            New-AzResourceGroup -Name $Env:RESOURCE_GROUP_NAME -Location $Env:STORAGE_ACCOUNT_LOCATION
            $Param = @{
              ResourceGroupName = $Env:RESOURCE_GROUP_NAME
              Name              = $Env:STORAGE_ACCOUNT_NAME
              Location          = $Env:STORAGE_ACCOUNT_LOCATION
              SkuName           = $Env:STORAGE_ACCOUNT_SKU
            }
            $StorageAccount = New-AzStorageAccount @Param
            New-AzStorageContainer -Name $Env:STORAGE_CONTAINER_NAME -Context $StorageAccount.Context
          azPSVersion: latest
        env:
          RESOURCE_GROUP_NAME: ${{secrets.RESOURCE_GROUP_NAME}}
          STORAGE_ACCOUNT_NAME: ${{secrets.STORAGE_ACCOUNT}}
          STORAGE_CONTAINER_NAME: ${{secrets.CONTAINER_NAME}}
          STORAGE_ACCOUNT_LOCATION: West Europe
          STORAGE_ACCOUNT_SKU: Standard_LRS
